---
- name:  query inventory {{ inventory }}
  import_role:
    name: ba-at
    tasks_from: get_inventory
  vars:
    tower_ip: "{{ lookup('env', 'TOWER_HOST') }}"
    login_user: "{{ lookup('env', 'TOWER_USERNAME') }}"
    login_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    inventory_name: "{{ inventory }}"

- name: checking and assinging inventory id, if get call success
  set_fact:
    in_id: "{{ inv.json.results[0].id }}"
  when: inv.json.results is defined

# - name: checking and assinging inventory id, if create call success
#   set_fact:
#     in_id: "{{ inv.json.id }}"
#   when: inv.json.id is defined and inv.json.id != ""

- name: Split and Create a list of the comma seperated Inventory group names
  set_fact:
      inventory_groups: "{{inventory_group_name.split(',')}}"

- debug:
    msg: "Inventory group list :- {{inventory_groups}} and Inventory group ID list :- {{grp_id}}"

- name: Check for multiple groups inside inventory {{inventory}}, create if it does not exists and strore the group IDs into a list
  include_tasks: check_and_create_groups.yml
  loop: "{{inventory_groups}}"

- debug:
    msg: "Inventory group list :- {{inventory_groups}} and Inventory group ID list :- {{grp_id}}"

- name: Query for host inside each group, add if it doesn't exists
  include_tasks: check_and_add_host_to_multiple_inventory_groups.yml
  loop: "{{grp_id}}"
