- name: Create shared image gallery
  azure_rm_gallery:
    client_id: "{{lookup('env', 'AZURE_CLIENT_ID')}}"
    secret: "{{lookup('env', 'AZURE_SECRET')}}"
    subscription_id: "{{lookup('env', 'AZURE_SUBSCRIPTION_ID')}}"
    tenant: "{{lookup('env', 'AZURE_TENANT')}}"
    resource_group: "{{ resource_group }}"
    name: "{{ shared_gallery_name }}"
    description: Contains Golden image for azure.
    tags:
       project: Automation_Factory