- name: Create custom image
  azure_rm_image:
    client_id: "{{lookup('env', 'AZURE_CLIENT_ID')}}"
    secret: "{{lookup('env', 'AZURE_SECRET')}}"
    subscription_id: "{{lookup('env', 'AZURE_SUBSCRIPTION_ID')}}"
    tenant: "{{lookup('env', 'AZURE_TENANT')}}"
    resource_group: "{{ resource_group }}"
    name: "{{ image_name }}"
    os_type: "{{os|capitalize}}"
    source: "https://{{storage_account}}.blob.core.windows.net/{{container}}/Microsoft.Compute/Images/{{image_type}}/{{ blob_url }}"
    tags:
       project: Automation_Factory