- name: Get facts by name
  azure_rm_virtualmachine_info:
    client_id: "{{lookup('env', 'AZURE_CLIENT_ID')}}"
    secret: "{{lookup('env', 'AZURE_SECRET')}}"
    subscription_id: "{{lookup('env', 'AZURE_SUBSCRIPTION_ID')}}"
    tenant: "{{lookup('env', 'AZURE_TENANT')}}"
    resource_group: "{{resource_group}}"
    name: "{{vm_name}}"
  register: vm_info

- debug:
     msg: "{{vm_info}}"