---
- name : Add group
  uri :
        url : "{{tower_ip}}/api/v2/inventories/{{inv.json.id}}/groups/"
        user: "{{ login_user }}"
        password: "{{ login_password }}"
        method : POST
        body : >
          { "description" : "{{ group_description }}",
            "name": "{{ group_name }}"
          }
        force_basic_auth: yes
        validate_certs : no
        body_format: json
        status_code: 201
  register: group_out

- name : Add host to group {{group_out.json.name}}
  uri :
    url : "{{tower_ip}}/api/v2/groups/{{group_out.json.id}}/hosts/"
    user: "{{ login_user }}"
    password: "{{ login_password }}"
    method : POST
    body : >
      { "description" : "{{ item.description }}",
        "name": "{{ item.name }}",
        "inventory": "{{group_out.json.inventory}}"
       }
    force_basic_auth: yes
    validate_certs : no
    body_format: json
    status_code:
      - 200
      - 201
      - 202
      - 204
  # delegate_to: localhost
  register : host_out
  with_items:
    - "{{ list_of_hosts }}"

