
- name : Create an organization
  uri :
    url : "{{tower_ip}}/api/v2/organizations/"
    user: "{{ login_user }}"
    password: "{{ login_password }}"

    method : POST
    body : >
      { "description" : "{{ org_desc}}",
        "name": "{{ org_name}}",
      }
    force_basic_auth: yes
    validate_certs : no
    body_format: json
    status_code: 201
  # delegate_to: localhost
  register : org
