- name : Get credential type ID for {{ cred_type }}
  uri :
    url : "{{ tower_ip }}/api/v2/credential_types/?name={{ cred_type }}"
    user : "{{ login_user }}"
    password : "{{ login_password }}"
    method : GET
    force_basic_auth: yes
    validate_certs : no
    body_format: json
    status_code:
        - 201
        - 200
        - 204
  # delegate_to: localhost
  register : cred_out

- name : Creating {{ cred_name }} credential
  uri :
    url : "{{tower_ip}}/api/v2/organizations/{{ org_id }}/credentials/"
    user: "{{ login_user }}"
    password: "{{ login_password }}"

    method : POST
    body : >
      { "description" : "{{ cred_type }} credential Created from tower automation",
        "credential_type" : "{{ cred_out.json.results[0].id }}",
        "name": "{{ cred_name }}",
        "organization" : "{{ org_id}}",
        "kind" : "{{cred_kind}}",
        "inputs": {
            "vault_password": "{{ cred_password}}"
        }
       }
    force_basic_auth: yes
    validate_certs : no
    body_format: json
    status_code: 201
  # delegate_to: localhost
  register : cred
