---
- name : query scm credential details by name {{ git_cred_name}}
  uri :
    url : "{{tower_ip}}/api/v2/organizations/{{ org_id }}/?name={{ git_cred_name}}"
    user: "{{ login_user }}"
    password: "{{ login_password }}"

    method : GET
    force_basic_auth: yes
    validate_certs : no
    body_format: json
    status_code:
        - 201
        - 200
        - 204
  # delegate_to: localhost
  register : scm_cred
